### ISSUE TITLE
isValidMove() inside Column.java does not work

### ISSUE THREAD

**Issue by msosborne3** [kenbonilla/FourRowSolitaire#4]
A line in isValidMove() returns false when it should return true. As a result, only kings qualify as valid moves. Any other card will not be able to be added.

`
      ...  else if(!isEmpty() && card.getColor() != peek().getColor() && card.getNumber() == (peek().getNumber() - 1))
        {
            return false;
} ...
`

the else if statement should return true.
`...
else if(!isEmpty() && card.getColor() != peek().getColor() && card.getNumber() == (peek().getNumber() - 1))
        {
            return true;
        }
...`

**Comment by kenbonilla** [comment]
Bug has been squashed
