### ISSUE TITLE
Error with push() in Column class

### ISSUE THREAD

**Issue by msosborne3** [kenbonilla/FourRowSolitaire#7]
push() does not check if the column is empty before comparing the new card to the card in the column. As a result, there is not necessarily something to compare the card to.

originally: 
`else if(card.getColor() != peek().getColor() && card.getNumber() == peek().getNumber() - 1)
        {
            super.push(card);
            return card;
        }`

Should be:
`else if(!isEmpty() && card.getColor() != peek().getColor() && card.getNumber() == peek().getNumber() - 1)
        {
            super.push(card);
            return card;
        }`

**Comment by kenbonilla** [comment]
If we trace calls, CardStack.java is as follows

```    
public synchronized Card peek()
    {
	if (cards.isEmpty())
        {
            return null;
        }

```

such that if the column is empty and `card.getNumber() == peek().getNumber() - 1` will fail. Therefore I do not think that `!isEmpty()` is a necessary call for this method.
I'm leaving the bug open for now, if I'm reading the code wrong let me know.

**Comment by msosborne3** [comment]
I don't think that that is run before the conditional in Column peek(). I've tried running the tests with !isEmpty() and without and they pass with !isEmpty() and fail without. It seems that it is comparing the card to a null value

**Comment by msosborne3** [comment]
I went ahead and updated the file before I saw your comment, but I can change it if you still disagree.

**Comment by msosborne3** [comment]
Fixed bug in Column class

**Comment by kenbonilla** [comment]
Your change doesn't break anything so I'm fine with it staying

**Comment by msosborne3** [comment]
By the way, I realized that the real issue it was creating is that it almost always throws a NullPointerException
